DROP TABLE IF EXISTS stocks;

create table stocks (
  id serial primary key,
  date varchar(255),
  ticker varchar(255),
  name varchar(255),
  sicsector varchar(255),
  sicindustry varchar(255),
  famaindustry varchar(255),
  sector varchar(255),
  industry varchar(255),
  scalemarketcap varchar(255),
  scalerevenue varchar(255),
)

CREATE TABLE `financials` (
  `id` serial primary key,
  `ticker` varchar(5) NOT NULL,
  `date` date NOT NULL,
  `accoci` int(11) DEFAULT NULL,
  `assets` bigint(11) DEFAULT NULL,
  `assetsavg` bigint(11) DEFAULT NULL,
  `assetsc` bigint(11) DEFAULT NULL,
  `assetsnc` bigint(11) DEFAULT NULL,
  `assetturnover` bigint(11) DEFAULT NULL,
  `bvps` bigint(11) DEFAULT NULL,
  `capex` bigint(11) DEFAULT NULL,
  `cashneq` bigint(11) DEFAULT NULL,
  `cashnequsd` bigint(11) DEFAULT NULL,
  `cor` bigint(11) DEFAULT NULL,
  `consolinc` bigint(11) DEFAULT NULL,
  `currentratio` bigint(11) DEFAULT NULL,
  `de` bigint(11) DEFAULT NULL,
  `debt` bigint(11) DEFAULT NULL,
  `debtc` bigint(11) DEFAULT NULL,
  `debtnc` bigint(11) DEFAULT NULL,
  `debtusd` bigint(11) DEFAULT NULL,
  `deferredrev` bigint(11) DEFAULT NULL,
  `depamor` bigint(11) DEFAULT NULL,
  `deposits` bigint(11) DEFAULT NULL,
  `divyield` bigint(11) DEFAULT NULL,
  `dps` bigint(11) DEFAULT NULL,
  `ebit` bigint(11) DEFAULT NULL,
  `ebitda` bigint(11) DEFAULT NULL,
  `ebitdamargin` bigint(11) DEFAULT NULL,
  `ebitdausd` bigint(11) DEFAULT NULL,
  `ebitusd` bigint(11) DEFAULT NULL,
  `ebt` bigint(11) DEFAULT NULL,
  `eps` float DEFAULT NULL,
  `epsdil` float DEFAULT NULL,
  `epsusd` float DEFAULT NULL,
  `equity` bigint(11) DEFAULT NULL,
  `equityavg` bigint(11) DEFAULT NULL,
  `equityusd` bigint(11) DEFAULT NULL,
  `ev` bigint(11) DEFAULT NULL,
  `evebit` bigint(11) DEFAULT NULL,
  `fcf` bigint(11) DEFAULT NULL,
  `fcfps` bigint(11) DEFAULT NULL,
  `fxusd` bigint(11) DEFAULT NULL,
  `gp` bigint(11) DEFAULT NULL,
  `grossmargin` float DEFAULT NULL,
  `intangibles` bigint(11) DEFAULT NULL,
  `intexp` bigint(11) DEFAULT NULL,
  `invcap` bigint(11) DEFAULT NULL,
  `inventory` bigint(11) DEFAULT NULL,
  `investments` bigint(11) DEFAULT NULL,
  `investmentsc` bigint(11) DEFAULT NULL,
  `investmentsnc` bigint(11) DEFAULT NULL,
  `liabilities` bigint(11) DEFAULT NULL,
  `liabilitiesc` bigint(11) DEFAULT NULL,
  `liabilitiesnc` bigint(11) DEFAULT NULL,
  `marketcap` bigint(11) DEFAULT NULL,
  `ncf` bigint(11) DEFAULT NULL,
  `ncfbus` bigint(11) DEFAULT NULL,
  `ncfcommon` bigint(11) DEFAULT NULL,
  `ncfdebt` bigint(11) DEFAULT NULL,
  `ncfdiv` bigint(11) DEFAULT NULL,
  `ncff` bigint(11) DEFAULT NULL,
  `ncfi` bigint(11) DEFAULT NULL,
  `ncfinv` bigint(11) DEFAULT NULL,
  `ncfo` bigint(11) DEFAULT NULL,
  `ncfx` bigint(11) DEFAULT NULL,
  `netinc` bigint(11) DEFAULT NULL,
  `netinccmn` bigint(11) DEFAULT NULL,
  `netinccmnusd` bigint(11) DEFAULT NULL,
  `netincdis` bigint(11) DEFAULT NULL,
  `netincnci` bigint(11) DEFAULT NULL,
  `netmargin` bigint(11) DEFAULT NULL,
  `opex` bigint(11) DEFAULT NULL,
  `opinc` bigint(11) DEFAULT NULL,
  `payables` bigint(11) DEFAULT NULL,
  `payoutratio` bigint(11) DEFAULT NULL,
  `pb` float DEFAULT NULL,
  `pe` float DEFAULT NULL,
  `pe1` float DEFAULT NULL,
  `ppnenet` bigint(11) DEFAULT NULL,
  `prefdivis` bigint(11) DEFAULT NULL,
  `price` bigint(11) DEFAULT NULL,
  `ps` float DEFAULT NULL,
  `ps1` float DEFAULT NULL,
  `receivables` bigint(11) DEFAULT NULL,
  `retearn` bigint(11) DEFAULT NULL,
  `revenue` bigint(11) DEFAULT NULL,
  `revenueusd` bigint(11) DEFAULT NULL,
  `rnd` bigint(11) DEFAULT NULL,
  `roa` float DEFAULT NULL,
  `roe` float DEFAULT NULL,
  `roic` float DEFAULT NULL,
  `ros` float DEFAULT NULL,
  `sbcomp` bigint(11) DEFAULT NULL,
  `sgna` bigint(11) DEFAULT NULL,
  `sharefactor` bigint(11) DEFAULT NULL,
  `sharesbas` bigint(11) DEFAULT NULL,
  `shareswa` bigint(11) DEFAULT NULL,
  `shareswadil` bigint(11) DEFAULT NULL,
  `sps` float DEFAULT NULL,
  `tangibles` bigint(11) DEFAULT NULL,
  `taxassets` bigint(11) DEFAULT NULL,
  `taxexp` bigint(11) DEFAULT NULL,
  `taxliabilities` bigint(11) DEFAULT NULL,
  `tbvps` float DEFAULT NULL,
  `workingcapital` bigint(11) DEFAULT NULL
);

-- Table: public.financials

DROP TABLE IF EXISTS public.indicators;

CREATE TABLE IF NOT EXISTS public.indicators
(
    index serial,
	"table" varchar(255),
	indicator varchar(255),
	isfilter varchar(1),
	isprimarykey varchar(1),
	title varchar(255),
	description varchar(255),
	unittype varchar(255)
);

ALTER TABLE IF EXISTS public.indicators
    OWNER to ubuntu;